// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReRoute from "../ReRoute.bs.js";
import * as RouterConfig from "./RouterConfig.bs.js";

var Router = ReRoute.CreateRouter(RouterConfig);

export {
  Router ,
  
}
/* Router Not a pure module */
