// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Admin(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Admin"), React.createElement("p", undefined, "This is an admin page"));
}

var make = Admin;

export {
  make ,
  
}
/* react Not a pure module */
