// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NotFound(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "We are sorry..."), React.createElement("p", undefined, "Unfortunately we could not find the page you were looking for."), React.createElement("p", undefined, "Use the above menu to navigate to other pages :)"));
}

var make = NotFound;

export {
  make ,
  
}
/* react Not a pure module */
