// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.bs.js";
import * as Admin from "./pages/Admin.bs.js";
import * as React from "react";
import * as Router from "./router/Router.bs.js";
import * as NotFound from "./pages/NotFound.bs.js";
import * as ReactDom from "react-dom";

((require ('./App.css')));

function App$App(Props) {
  return React.createElement(Router.Router.Container.make, {
              children: (function (currentRoute) {
                  var tmp;
                  switch (currentRoute) {
                    case /* Admin */0 :
                        tmp = React.createElement(Admin.make, {});
                        break;
                    case /* Home */1 :
                        tmp = React.createElement(Home.make, {});
                        break;
                    case /* NotFound */2 :
                        tmp = React.createElement(NotFound.make, {});
                        break;
                    
                  }
                  return React.createElement("div", undefined, React.createElement("ul", undefined, React.createElement("h3", undefined, "Menu"), React.createElement(Router.Router.Link.make, {
                                      route: /* Home */1,
                                      children: React.createElement("li", undefined, "Home")
                                    }), React.createElement(Router.Router.Link.make, {
                                      route: /* Admin */0,
                                      children: React.createElement("li", undefined, "Admin")
                                    })), tmp);
                })
            });
}

var App = {
  make: App$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Couldn't find #root element to mount the React app.");
} else {
  ReactDom.render(React.createElement(App$App, {}), root);
}

export {
  App ,
  
}
/*  Not a pure module */
