// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var push = RescriptReactRouter.push;

var replace = RescriptReactRouter.replace;

var watchUrl = RescriptReactRouter.watchUrl;

var unwatchUrl = RescriptReactRouter.unwatchUrl;

var dangerouslyGetInitialUrl = RescriptReactRouter.dangerouslyGetInitialUrl;

var useUrl = RescriptReactRouter.useUrl;

export {
  push ,
  replace ,
  watchUrl ,
  unwatchUrl ,
  dangerouslyGetInitialUrl ,
  useUrl ,
  
}
/* RescriptReactRouter Not a pure module */
